"""initial schema

Revision ID: 07bd253a84e4
Revises:
Create Date: 2026-08-15 14:15:15.480921
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "07bd253a84e4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbound_deliveries",
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbound_deliveries")),
    )
    with op.batch_alter_table("inbound_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inbound_deliveries_event_name"), ["event_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_inbound_deliveries_source"), ["source"], unique=False)

    op.create_table(
        "rate_limit_counters",
        sa.Column("bucket_key", sa.String(length=255), nullable=False),
        sa.Column("window_start", sa.Integer(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("bucket_key", "window_start", name=op.f("pk_rate_limit_counters")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.String(length=255), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "webhook_endpoints",
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("event_types", sa.Text(), nullable=False),
        sa.Column("signing_secret", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_endpoints")),
    )
    with op.batch_alter_table("webhook_endpoints", schema=None) as batch_op:
        batch_op.create_index("ix_webhook_endpoints_active", ["is_active"], unique=False)

    op.create_table(
        "api_keys",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("key_digest", sa.String(length=64), nullable=False),
        sa.Column("scopes", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_api_keys_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index("ix_api_keys_active", ["revoked_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_keys_key_digest"), ["key_digest"], unique=True)
        batch_op.create_index(batch_op.f("ix_api_keys_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_event_name"), ["event_name"], unique=False
        )
        batch_op.create_index(
            "ix_audit_events_name_time", ["event_name", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_subject_id"), ["subject_id"], unique=False
        )
        batch_op.create_index(
            "ix_audit_events_subject_time", ["subject_id", "created_at"], unique=False
        )

    op.create_table(
        "items",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_items_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_items_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index("ix_items_owner_status", ["owner_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_status"), ["status"], unique=False)

    op.create_table(
        "webhook_deliveries",
        sa.Column("endpoint_id", sa.String(length=64), nullable=False),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column("request_body", sa.Text(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("succeeded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["webhook_endpoints.id"],
            name=op.f("fk_webhook_deliveries_endpoint_id_webhook_endpoints"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_deliveries")),
    )
    with op.batch_alter_table("webhook_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webhook_deliveries_endpoint_id"), ["endpoint_id"], unique=False
        )
        batch_op.create_index(
            "ix_webhook_deliveries_endpoint_time", ["endpoint_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_webhook_deliveries_event_name"), ["event_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_webhook_deliveries_response_status"), ["response_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_webhook_deliveries_subject_id"), ["subject_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webhook_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webhook_deliveries_subject_id"))
        batch_op.drop_index(batch_op.f("ix_webhook_deliveries_response_status"))
        batch_op.drop_index(batch_op.f("ix_webhook_deliveries_event_name"))
        batch_op.drop_index("ix_webhook_deliveries_endpoint_time")
        batch_op.drop_index(batch_op.f("ix_webhook_deliveries_endpoint_id"))

    op.drop_table("webhook_deliveries")
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_items_status"))
        batch_op.drop_index("ix_items_owner_status")
        batch_op.drop_index(batch_op.f("ix_items_owner_id"))
        batch_op.drop_index(batch_op.f("ix_items_name"))

    op.drop_table("items")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_events_subject_time")
        batch_op.drop_index(batch_op.f("ix_audit_events_subject_id"))
        batch_op.drop_index("ix_audit_events_name_time")
        batch_op.drop_index(batch_op.f("ix_audit_events_event_name"))
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_id"))

    op.drop_table("audit_events")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_owner_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_key_digest"))
        batch_op.drop_index("ix_api_keys_active")

    op.drop_table("api_keys")
    with op.batch_alter_table("webhook_endpoints", schema=None) as batch_op:
        batch_op.drop_index("ix_webhook_endpoints_active")

    op.drop_table("webhook_endpoints")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("rate_limit_counters")
    with op.batch_alter_table("inbound_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inbound_deliveries_source"))
        batch_op.drop_index(batch_op.f("ix_inbound_deliveries_event_name"))

    op.drop_table("inbound_deliveries")
    # ### end Alembic commands ###
